### ISSUE TITLE
endplay.interact - shuffle - Encountered an unexpected error while executing

### ISSUE THREAD

**Issue by ackhh** [dominicprice/endplay#17]
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)] on win32
pip show endplay
Name: endplay
Version: 0.4.8b0

python -m endplay.interact
N> shuffle
Encountered an unexpected error while executing: InteractiveDeal.reset() takes 1 positional argument but 2 were given
N>
N> shuffle hcp(north) > 15
Encountered an unexpected error while executing: InteractiveDeal.reset() takes 1 positional argument but 2 were given
N>

**Comment by dominicprice** [comment]
mea culpa, using master as a working tree...fixed and running CI now; will tag and push to pypi later
