### ISSUE TITLE
solve_board() returns negative trick values

### ISSUE THREAD

**Issue by markgonzalez2** [dominicprice/endplay#18]
```
d = Deal("N:987... K45... AQ2... T63...", first = Player.west, trump = Denom.spades)
d.play("S6")
for card, tricks in solve_board(d):
    print(card, tricks)
```

This code outputs:
> ♠7 -2
> ♠8 -2
> ♠9 -2

Change the 9 to a J and you get the correct output:
> ♠7 3
> ♠8 3
> ♠J 2

**Comment by markgonzalez2** [comment]
It seems that -2 denotes that all playable cards are equal (e.g., a singleton). Can this behavior be toggled?

**Comment by dominicprice** [comment]
Ah, I hadn’t noticed that…thanks for letting me know - yes I think you’re right, it’s probably one of the flags passed to the dds library. I’ll have a look this afternoon when i get back from work.

**Comment by dominicprice** [comment]
Yep was using the wrong `mode` flag..fix pushed to master branch, CI is running now and assuming it passes I'll tag and push to PyPI in the morning.

**Comment by dominicprice** [comment]
fixed in 0.4.10, you should be able to update via pypi now :).

**Comment by markgonzalez2** [comment]
```
d = Deal("N:987... K45... AQ2... T63...", first = Player.west, trump = Denom.spades)
d.play("S6")
for solution in solve_all_boards([d]):
    try:
        for card, tricks in solution:
            print(card, tricks)
    except TypeError:
        break
```
This slightly modified code still outputs the negative values.

**Comment by dominicprice** [comment]
Mea culpa, I don't get to play around with this as much nowadays so I forget how it works.

CI running now with same fix as before, and also fixed the iteration of `SolvedBoardList` so you don't have to catch the `TypeError` (I was returning not raising an `IndexError`....)

**Comment by dominicprice** [comment]
ok hopefully the version now on pypi fixes this issue for good now XD
