### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by ThorvaldAagaard** [dominicprice/endplay#19]
I tried this command

```pip install endplay```

running on a windows 11 in an administrator prompt and got the error

```
Collecting endplay
  Using cached endplay-0.4.11b0.tar.gz (227 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
```
.... a long trace endning with 
```
AppData\Local\Temp\pip-build-env-xs4bq7px\overlay\Lib\site-packages\setuptools\config\pyprojecttoml.py", line 55, in validate
          raise ValueError(f"{error}\n{summary}") from None
      ValueError: invalid pyproject.toml config: `project`.
      configuration error: `project` must contain ['name'] properties
      [end of output]
```

Pip has the following version
```
C:\WINDOWS\system32>pip -V
pip 23.1.2 from X:\Python311\Lib\site-packages\pip (python 3.11)
```

**Comment by dominicprice** [comment]
Hi,
Thanks for bringing this up, apparantly some of the tooling I was using in the build system has now been officially deprecated causing the issue. I have created a branch with a fix which is now running CI, if all well then I will push to PyPI tomorrow.

In the meantime, if you can try installing directly from the branch with the command
`pip install git+https://github.com/dominicprice/endplay@build_hotfix`
and let me know if that now works for you then that would be very helpful.

Thanks,
Dominic

**Comment by ThorvaldAagaard** [comment]
Installation using the hotfix-build worked fine
