### ISSUE TITLE
generate_deal() specifying predeal throws AttributeError

### ISSUE THREAD

**Issue by BSalita** [dominicprice/endplay#9]
I'm trying to use endplay.dealer.generate_deal(() with constraints and predeal args. I'm unable to use predeal in any form because it raises an AttributeError exception.

    import endplay

    constraints = "hcp(north) > 10"
    predeal = endplay.types.deal.Deal()

    d = endplay.dealer.generate_deal(constraints, predeal) # AttributeError: 'Deal' object has no attribute 'dtype'

**Comment by dominicprice** [comment]
You need to specify the predeal as a keyword argument, try
```
endplay.dealer.generate_deal(constraints, predeal=predeal)
```
and it should work. The first argument to `generate_deal` is an `*args` style parameter so it will swallow up any arguments which aren't named and assume they are meant to be constraints.

**Comment by BSalita** [comment]
Yea, that's undoubtedly the solution.
